version: "3.7"

services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    volumes:
      - mdb:/var/lib/mysql
    expose:
        - "3306"
    env_file:
      - .env
    networks:
      - inception_net
    restart: on-failure
  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    volumes:
      - wp:/var/www/html
    depends_on:
      - mariadb
    env_file:
      - .env
    networks:
      - inception_net
    expose:
      - "9000"
    restart: on-failure
  
  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    volumes:
      - wp:/var/www/html
    ports:
      - 443:443
    networks:
      - inception_net
    depends_on:
      - wordpress
    env_file:
      - .env
    restart: on-failure

  redis:
    build: ./requirements/bonus/redis
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - inception_net
    restart: on-failure

volumes:
  mdb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/yichan/data/mysql

  wp:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/yichan/data/wordpress

  # prometheus:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     o: bind
  #     device: /home/yichan/data/prometheus

networks:
   inception_net:
    driver: bridge