version: "3"

services:
  nginx:
    container_name: nginx
    build: requirements/nginx
    volumes:
      - wordpress:/var/www/html
    ports:
      - "443:443"
    networks:
      - network
    env_file:
      - .env
    depends_on:
      - wordpress
    restart: unless-stopped
    
  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - network
    env_file:
      - .env
    healthcheck: 
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - network
    env_file:
      - .env
    depends_on:
      mariadb:
        condition: service_healthy
    restart: unless-stopped

#BONUS_PART

  # adminer:
  #   build: requirements/bonus/adminer
  #   networks:
  #     - network
  #   restart: unless-stopped

  # static:
  #   build: requirements/bonus/static
  #   networks:
  #     - network
  #   env_file:
  #     - .env
  #   restart: unless-stopped

  # redis:
  #   build: requirements/bonus/redis
  #   networks:
  #     - network
  #   restart: unless-stopped

  # ftp:
  #   build: requirements/bonus/ftp
  #   volumes:
  #     - files:/var/www/html
  #   networks:
  #     - network
  #   env_file:
  #     - .env
  #   ports:
  #     - "20:20"
  #     - "21:21"
  #     - "40000-40002:40000-40002"
  #   restart: unless-stopped

  # prometheus:
  #   build: requirements/bonus/prometheus
  #   volumes:
  #     - prometheus:/var/lib/prometheus
  #   networks:
  #     - network
  #   restart: unless-stopped

  # node_exporter:
  #   build: requirements/bonus/node_exporter
  #   networks:
  #     - network
  #   restart: unless-stopped

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/yichan/data/mariadb

  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/yichan/data/wordpress

  # prometheus:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     o: bind
  #     device: /home/yichan/data/prometheus

networks:
  network:
    driver: bridge